---
title: "Census Data"
---

```{r load_packages}
library(tidyverse)
library(lubridate)
library(here)
library(tigris)
library(sf)
library(devtools)
library(cowplot)
library(ggthemes)
library(ggsflabel)
library(glue)
library(tidycensus)

devtools::load_all()
```

```{r}
census_api_key(
  readRDS(file.path(here::here(), 'data/census_api_key.rds')), 
install = TRUE,
overwrite = TRUE)
```

```{r}
options(tigris_use_cache = TRUE)

ny <- get_acs(geography = "tract", 
              variables = "B19013_001", 
              state = "NY", 
              county = "New York", 
              geometry = TRUE)

ggplot(ny, aes(fill = estimate)) + 
  geom_sf() + 
  theme_void() + 
  scale_fill_viridis_c(labels = scales::dollar)
```

```{r}
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")

harris <- get_decennial(geography = "tract", variables = racevars, 
                  state = "TX", county = "Harris County", geometry = TRUE,
                  summary_var = "P001001") 

harris %>%
  mutate(pct = 100 * (value / summary_value)) %>%
  ggplot(aes(fill = pct)) +
  facet_wrap(~variable) +
  geom_sf(color = NA) +
  # coord_sf(crs = 26915) + # Appropriate CRS for Houston, but may not be for your data
  scale_fill_viridis_c()
```

```{r}
ny <- get_acs(geography = "tract", 
              variables = "B19013_001", 
              state = "NY", 
              county = c("New York", "Bronx", "Kings", "Queens", "Richmond"), 
              geometry = TRUE)
```

```{r fig.height = 6, fig.width = 6}
ggplot(ny, aes(fill = estimate)) + 
  geom_sf() + 
  theme_void() + 
  scale_fill_viridis_c(labels = scales::dollar)
```

```{r}
ny <- get_decennial(geography = "tract", variables = racevars, 
                  state = "NY", 
                  county = c("New York", "Bronx", "Kings", "Queens", "Richmond"), 
                  geometry = TRUE,
                  summary_var = "P001001") 
```

```{r fig.height = 6, fig.width = 6}
ny %>%
  mutate(pct = 100 * (value / summary_value)) %>%
  ggplot(aes(fill = pct)) +
  facet_wrap(~variable) +
  geom_sf(color = NA) +
  scale_fill_viridis_c() +
  theme_hc()
```








